apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: landing-tls
spec:
  secretName: landing-tls
  issuerRef:
    name: letsencrypt
    kind: ClusterIssuer
  dnsNames:
    - dubrovskih.ru
